%YAML 1.1
---
application:
  title: Appspand Chat Server configuration for production environment
  module: chat.main:main
  version: 1.0
  revision: 1
  stage: production

# Debugging
debug: false

# Identity
server:
  hosts:
    - host: chat.appspand.com
    - host: chat.dev.appspand.com
    - host: chat.appspandapp.com
    - host: chat.dev.appspandapp.com
  base_port: 8200

# Databases
database:
  mongodb:
    connection_uri: mongodb://10.0.1.32:27017/chat
    connection_pool: 3
    timeout: 5000

  redis:
    enabled: true
    connection_uri: redis://10.0.1.21:6379/1
    connection_pool: 3
    timeout: 5000
    host: 10.0.1.21
    port: 6379
    password: !!str
    db: 1

# Session
session:
  timeout_minutes: 60

# Interop
interop:
  sqs:
    access_key: AKIAIFHFM4CZA26UVV4A
    secret_key: 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
    region: ap-southeast-1
    path: /
    request_queue_name: MSG_FROM_SNEK_TO_APPSPAND
    fallback_queue_name: MSG_FROM_APPSPAND_TO_SNEK
...
