#!/usr/bin/env python
# This Python file uses the following encoding: utf-8
#
# Copyright 2013 Appspand

import logging
import sys

# try:
# 	import insights
# except:
# 	print 'Insights is not installed'
# 	sys.exit()

from dataview.daemon import Daemon
from dataview.server import application
from dataview.core import settings
from dataview import __version__
import tornado.ioloop

PIDFILE = '/var/run/dataviewd.pid'
# Keep all log files in one place
LOGFILE = '/usr/local/insights/dataviewd.log'

# Configure logging
logging.basicConfig(filename=LOGFILE, level=logging.DEBUG)

class DataViewWebDaemon(Daemon):

    def run(self):
        application.listen(int(settings.WEB_APP['port']))
        tornado.ioloop.IOLoop.instance().start()

if __name__ == "__main__":

    daemon = DataViewWebDaemon(PIDFILE)

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            try:
                print 'Starting DataView Web Daemon at {0}:{1}'.format(settings.WEB_APP['host'],
                        settings.WEB_APP['port'])
                daemon.start()
            except:
                pass
        elif 'stop' == sys.argv[1]:
            print "Stopping DataView WebDaemon ..."
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            print 'Restarting DataView WebDaemon at {0}:{1}'.format(settings.WEB_APP['host'],
                        settings.WEB_APP['port'])
            daemon.restart()
        elif 'status' == sys.argv[1]:
            try:
                pf = file(PIDFILE, 'r')
                pid = int(pf.read().strip())
                pf.close()
            except IOError:
                pid = None
            except SystemExit:
                pid = None

            if pid:
                print 'DataView WebDaemon {0} is running as pid {1}'.format(__version__, pid)
                print 'You can check it out at {0}:{1}'.format(settings.WEB_APP['host'],
                        settings.WEB_APP['port'])
            else:
                print 'DataView WebDaemon {0} is not running.'.format(__version__)

        else:
            print "Unknown command"
            sys.exit(2)
            sys.exit(0)
    else:
        print "usage: %s start|stop|restart|status" % sys.argv[0]
        sys.exit(2)

